### ISSUE TITLE
Add roles support to add command

### ISSUE THREAD

**Issue by lombad** [codecovevienna/gittt-cli#124]
As a user I want to be able to set a `role` by using the `gittt add` command.

AC:
- `gittt add` asks for role
- Sets role for record

**Comment by eiabea** [comment]
This is already implemented, the `.gittt.yml` file has to include the `requiresRoles` parameter

```
name: awesome_project_1
requiresRoles: true
```

**Comment by lombad** [comment]
Absolutely awesome :+1:
