### ISSUE TITLE
Handle migration of git repository

### ISSUE THREAD

**Issue by eiabea** [codecovevienna/gittt-cli#18]
If a project gets moved from e.g. GitLab to github the url/port (which is used to identify the project) gets changed and gets treated like a new project. This should be handled by a migration process.

1. Before a new project gets created automatically the user should be asked if he wants to migrate from an other project to this one
2. Rename old project directory
3. Commit renamed directory
4. Edit any existing links
5. Commit links
6. Push changes

**Comment by matthiaseigner** [comment]
maybe add another commit and push step to it? so it is correctly stored at the server?
