### ISSUE TITLE
Error if initialized outside of a git repository

### ISSUE THREAD

**Issue by lombad** [codecovevienna/gittt-cli#25]
If the command `gittt init` is called outside of a git repository an UnhandledPromiseRejection error is thrown.

**Comment by lombad** [comment]
The problem is usually not present for developers, because the gittt-cli folder is a git repository. So it adds per default the wrong folder as project.

It has to be decided whether the program prevents the user from using the folder in which the gittt is running for intialization or giving the notification that it will add "itself" as project.

For the released application this bug is still present.

**Comment by eiabea** [comment]
Moved to JIRA
